/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import javax.swing.*;
import java.awt.event.*;

public class KonversiSuhu extends javax.swing.JFrame {

    /** Creates new form KonversiSuhu */
    public KonversiSuhu() {
        initComponents();
        cmbKonversi.addItem("Celcius");
        cmbKonversi.addItem("Fahrenheit");
        cmbKonversi.addItem("Reamur");
        cmbKonversi.addItem("Kelvin");
txtSuhu.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '.') {
                    e.consume();
                }
            }
        });
txtSuhu.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                konversiSuhu();
            }

            private void konversiSuhu() {
               try {
            double suhuAwal = Double.parseDouble(txtSuhu.getText());
            String skalaAwal = cmbKonversi.getSelectedItem().toString();
            double hasil = 0;

            if (rbToCelcius.isSelected()) {
                hasil = toCelcius(suhuAwal, skalaAwal);
                lblHasil.setText("Hasil: " + hasil + " °C");
            } else if (rbToFahrenheit.isSelected()) {
                hasil = toFahrenheit(suhuAwal, skalaAwal);
                lblHasil.setText("Hasil: " + hasil + " °F");
            } else if (rbToReamur.isSelected()) {
                hasil = toReamur(suhuAwal, skalaAwal);
                lblHasil.setText("Hasil: " + hasil + " °Re");
            } else if (rbToKelvin.isSelected()) {
                hasil = toKelvin(suhuAwal, skalaAwal);
                lblHasil.setText("Hasil: " + hasil + " K");
            }

        } catch (NumberFormatException e) {
            lblHasil.setText("Masukkan angka yang valid.");
        }
            }
    private double toCelcius(double suhu, String skala) {
        switch (skala) {
        case "Fahrenheit":
            return (suhu - 32) * 5 / 9;
        case "Reamur":
            return suhu * 5 / 4;
        case "Kelvin":
            return suhu - 273.15;
        default:
            return suhu; // Jika skala sudah dalam Celcius, tidak ada konversi
    }
}


    private double toFahrenheit(double suhu, String skala) {
        switch (skala) {
            case "Celcius": return (suhu * 9 / 5) + 32;
            case "Reamur": return (suhu * 9 / 4) + 32;
            case "Kelvin": return (suhu - 273.15) * 9 / 5 + 32;
            default: return suhu;
        }
    }

    private double toReamur(double suhu, String skala) {
        switch (skala) {
            case "Celcius": return suhu * 4 / 5;
            case "Fahrenheit": return (suhu - 32) * 4 / 9;
            case "Kelvin": return (suhu - 273.15) * 4 / 5;
            default: return suhu;
        }
    }

    private double toKelvin(double suhu, String skala) {
        switch (skala) {
            case "Celcius": return suhu + 273.15;
            case "Fahrenheit": return (suhu - 32) * 5 / 9 + 273.15;
            case "Reamur": return suhu * 5 / 4 + 273.15;
            default: return suhu;
        }
    }   
   
}
        );

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        cmbKonversi = new javax.swing.JComboBox<>();
        rbToCelcius = new javax.swing.JRadioButton();
        rbToFahrenheit = new javax.swing.JRadioButton();
        rbToReamur = new javax.swing.JRadioButton();
        rbToKelvin = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setText("Masukkan Suhu");

        jLabel2.setText("Pilih Skala");

        jLabel3.setText("Hasil Konverksi");

        txtSuhu.setText("  ");
        txtSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuhuActionPerformed(evt);
            }
        });

        cmbKonversi.setBackground(new java.awt.Color(102, 255, 204));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtSuhu, org.jdesktop.beansbinding.ObjectProperty.create(), cmbKonversi, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        cmbKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKonversiActionPerformed(evt);
            }
        });

        rbToCelcius.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rbToCelcius);
        rbToCelcius.setText("Celcius");
        rbToCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbToCelciusActionPerformed(evt);
            }
        });

        rbToFahrenheit.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rbToFahrenheit);
        rbToFahrenheit.setText("Fahrenheit");

        rbToReamur.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rbToReamur);
        rbToReamur.setText("Reamur");

        rbToKelvin.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rbToKelvin);
        rbToKelvin.setText("Kelvin");

        btnKonversi.setBackground(new java.awt.Color(153, 255, 204));
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(102, 255, 204));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(102, 255, 204));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel4.setText("--( Aplikasi Konversi Suhu )--");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setText("Pilih Konversi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSuhu)
                                    .addComponent(cmbKonversi, 0, 195, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbToCelcius)
                                        .addGap(25, 25, 25)
                                        .addComponent(rbToFahrenheit)
                                        .addGap(34, 34, 34)
                                        .addComponent(rbToKelvin)
                                        .addGap(27, 27, 27)
                                        .addComponent(rbToReamur))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbToFahrenheit)
                    .addComponent(rbToReamur)
                    .addComponent(rbToCelcius)
                    .addComponent(rbToKelvin))
                .addGap(18, 18, 18)
                .addComponent(btnKonversi)
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasil)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbToCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbToCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbToCelciusActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
   
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuhuActionPerformed

    private void cmbKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKonversiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKonversiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
     System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     txtSuhu.setText("");
     lblHasil.setText("");
    rbToCelcius.setText("Celcius");
    rbToFahrenheit.setText("Fahrenheit");
    rbToKelvin.setText("Kelvin");
    rbToReamur.setText("Reamur");

txtSuhu.requestFocus();
   // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 java.awt.EventQueue.invokeLater(() -> new KonversiSuhu().setVisible(true));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JRadioButton rbToCelcius;
    private javax.swing.JRadioButton rbToFahrenheit;
    private javax.swing.JRadioButton rbToKelvin;
    private javax.swing.JRadioButton rbToReamur;
    private javax.swing.JTextField txtSuhu;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
